version: '3'

services:
  postgres:
    image: mdillon/postgis
    container_name: "postgres"
    hostname: "postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "pastdestinations"
    networks:
      - default

  proxy:
    build: .
    container_name: "proxy"
    hostname: "proxy"
    ports:
      - 5003:5003
    depends_on:
      - postgres
    networks:
      - default

networks:
  default:
    external:
      name: foo

